package Tablas;
// Generated 26-feb-2020 20:48:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * A generated by hbm2java
 */
public class A  implements java.io.Serializable {


     private String id;
     private String nombre;
     private String codigo;
     private Set bs = new HashSet(0);

    public A() {
    }

	
    public A(String id) {
        this.id = id;
    }
    public A(String id, String nombre, String codigo, Set bs) {
       this.id = id;
       this.nombre = nombre;
       this.codigo = codigo;
       this.bs = bs;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getBs() {
        return this.bs;
    }
    
    public void setBs(Set bs) {
        this.bs = bs;
    }




}


