package Tablas;
// Generated Mar 2, 2020 7:35:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * B generated by hbm2java
 */
public class B  implements java.io.Serializable {


     private int numerot;
     private String cliente;
     private String producto;
     private Integer lugar;
     private Integer cantidad;
     private Date fecha;
     private Boolean estado;

    public B() {
    }

	
    public B(int numerot) {
        this.numerot = numerot;
    }
    public B(int numerot, String cliente, String producto, Integer lugar, Integer cantidad, Date fecha, Boolean estado) {
       this.numerot = numerot;
       this.cliente = cliente;
       this.producto = producto;
       this.lugar = lugar;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.estado = estado;
    }
   
    public int getNumerot() {
        return this.numerot;
    }
    
    public void setNumerot(int numerot) {
        this.numerot = numerot;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public Integer getLugar() {
        return this.lugar;
    }
    
    public void setLugar(Integer lugar) {
        this.lugar = lugar;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


