package Tablas;
// Generated 26-feb-2020 20:48:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * B generated by hbm2java
 */
public class B  implements java.io.Serializable {


     private int numerot;
     private A a;
     private C c;
     private D d;
     private Integer cantidad;
     private Date fecha;
     private Boolean estado;

    public B() {
    }

	
    public B(int numerot) {
        this.numerot = numerot;
    }
    public B(int numerot, A a, C c, D d, Integer cantidad, Date fecha, Boolean estado) {
       this.numerot = numerot;
       this.a = a;
       this.c = c;
       this.d = d;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.estado = estado;
    }
   
    public int getNumerot() {
        return this.numerot;
    }
    
    public void setNumerot(int numerot) {
        this.numerot = numerot;
    }
    public A getA() {
        return this.a;
    }
    
    public void setA(A a) {
        this.a = a;
    }
    public C getC() {
        return this.c;
    }
    
    public void setC(C c) {
        this.c = c;
    }
    public D getD() {
        return this.d;
    }
    
    public void setD(D d) {
        this.d = d;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


