package Tablas;
// Generated 27-feb-2020 16:03:43 by Hibernate Tools 4.3.1



/**
 * C generated by hbm2java
 */
public class C  implements java.io.Serializable {


     private String nombre;
     private Integer precio;
     private String imagen;

    public C() {
    }

	
    public C(String nombre) {
        this.nombre = nombre;
    }
    public C(String nombre, Integer precio, String imagen) {
       this.nombre = nombre;
       this.precio = precio;
       this.imagen = imagen;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


