package Tablas;
// Generated 26-feb-2020 20:48:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * C generated by hbm2java
 */
public class C  implements java.io.Serializable {


     private String nombre;
     private Integer precio;
     private String imagen;
     private Set bs = new HashSet(0);

    public C() {
    }

	
    public C(String nombre) {
        this.nombre = nombre;
    }
    public C(String nombre, Integer precio, String imagen, Set bs) {
       this.nombre = nombre;
       this.precio = precio;
       this.imagen = imagen;
       this.bs = bs;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set getBs() {
        return this.bs;
    }
    
    public void setBs(Set bs) {
        this.bs = bs;
    }




}


