package Tablas;
// Generated Mar 2, 2020 7:35:40 PM by Hibernate Tools 4.3.1



/**
 * D generated by hbm2java
 */
public class D  implements java.io.Serializable {


     private int numero;
     private String nombre;
     private String lugar;
     private Integer valor;

    public D() {
    }

	
    public D(int numero) {
        this.numero = numero;
    }
    public D(int numero, String nombre, String lugar, Integer valor) {
       this.numero = numero;
       this.nombre = nombre;
       this.lugar = lugar;
       this.valor = valor;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }




}


